### ISSUE TITLE
IP Address Doesn't Log

### ISSUE THREAD

**Issue by veoux** [JeremyCrookshank/IP_History_Logs#12]
So, I just installed the plugin, and the IP Address doesn't appear to me. Other datas, like username, page, useragent and date appears.
![Screenshot_1](https://user-images.githubusercontent.com/59975900/72686412-2dda1980-3ad3-11ea-9b41-5cbd67f30a70.png)

**Comment by veoux** [comment]
The IP Address doesn't appear to be logged in database too.

![Screenshot_2](https://user-images.githubusercontent.com/59975900/72686425-5eba4e80-3ad3-11ea-876b-897964de7109.png)

**Comment by JeremyCrookshank** [comment]
Hey, can you confirm what version you're on and where you downloaded it from?

Cheers

**Comment by veoux** [comment]
Version 1.3.0. I downloaded from [MyBB Plugins Site](https://community.mybb.com/mods.php?action=view&pid=1213) and uploaded the content of admin and inc folders.

**Comment by JeremyCrookshank** [comment]
Is this happening for all users ip's or just your IP. If you like I can visit your site to see if it records my IP. Also do you use CloudFlare? Also can you screenshot your plugin settings.

Cheers

**Comment by veoux** [comment]
It seems to be happening with all users of the forum.

![Screenshot_1](https://user-images.githubusercontent.com/59975900/72762455-64409300-3bbe-11ea-86b3-28b6adc318c7.png)

Nope, I don't use Cloudflare. I set up to record everything but the page URL.

![Screenshot_2](https://user-images.githubusercontent.com/59975900/72762525-abc71f00-3bbe-11ea-86a8-440a56e5ff6a.png)

**Comment by JeremyCrookshank** [comment]
Any error log files in any of the plugin folders? Also what MyBB version are you on

**Comment by JeremyCrookshank** [comment]
Will close this soon if you don't reply. Let me know if its still occuring.

**Comment by JeremyCrookshank** [comment]
Closed. Feel free to reopen if required
