### ISSUE TITLE
Cloudflare Ip address showing but not show original ip address.

### ISSUE THREAD

**Issue by Casper2641** [JeremyCrookshank/IP_History_Logs#13]
Cloudflare Ip address showing but not show original ip address.

**Comment by JeremyCrookshank** [comment]
Hi Casper,

Thanks for the report. Can you confirm the attached setting is enabled in cloudflare?

![image](https://user-images.githubusercontent.com/46864828/76110787-100b3a00-5fd7-11ea-85a5-e9e3327a27a6.png)

**Comment by Casper2641** [comment]
Hi @JeremyCrookshank

Yes this function is enable.

![1](https://user-images.githubusercontent.com/59834696/76140453-8ce7f380-606b-11ea-8533-d766fefcdcc8.jpg)

**Comment by JeremyCrookshank** [comment]
Can you please create a new php file on the website in the root and place this in the file:

```
<?php

echo $_SERVER["HTTP_CF_CONNECTING_IP"]."\n";
echo $_SERVER['REMOTE_ADDR'];

?>
```

Make sure the files extension is .php

Then go directly to the file in your browser. Can you tell me if both ips are the same? And they both belong to cloudflare?

**Comment by Casper2641** [comment]
> Can you please create a new php file on the website in the root and place this in the file:
> 
> ```
> <?php
> 
> echo $_SERVER["HTTP_CF_CONNECTING_IP"]."\n";
> echo $_SERVER['REMOTE_ADDR'];
> 
> ?>
> ```
> 
> Make sure the files extension is .php
> 
> Then go directly to the file in your browser. Can you tell me if both ips are the same? And they both belong to cloudflare?

Thanks for reply but the problem continues.
Mybb shows the original IP address

![ip](https://user-images.githubusercontent.com/59834696/76144638-91c09d80-6093-11ea-86e6-da57f4bf2bdb.jpg)
![111](https://user-images.githubusercontent.com/59834696/76144639-92f1ca80-6093-11ea-9791-ac1746befaaa.jpg)

Mybb Real ip address screenshot

![originip](https://user-images.githubusercontent.com/59834696/76144739-4c50a000-6094-11ea-9d3a-c14f916c6bc9.jpg)

**Comment by JeremyCrookshank** [comment]
and if you goto yourwebsitehere.com/test.php what do you see?

**Comment by Casper2641** [comment]
> and if you goto yourwebsitehere.com/test.php what do you see?

![tess](https://user-images.githubusercontent.com/59834696/76160557-3dbdc380-613c-11ea-8d01-699653adaa79.jpg)

test php showed two ip addresses 
original and Cloudflare ip.
88.230.x.x - 162.158.34.x

**Comment by JeremyCrookshank** [comment]
Can you confirm the following:
Did you download the plugin from GitHub or Mybb Store?
Do you have many plugins. Any which may effect usage?
What MyBB version are you on?

Also can you try the following edit of the test.php file and then goto the test page again and see results


```
<?php

echo $_SERVER["HTTP_CF_CONNECTING_IP"]."\n";
echo $_SERVER['REMOTE_ADDR'];

if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
  	$_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
	}

echo $_SERVER["HTTP_CF_CONNECTING_IP"]."\n";
echo $_SERVER['REMOTE_ADDR'];

?>
```

**Comment by Casper2641** [comment]
> Can you confirm the following:
> Did you download the plugin from GitHub or Mybb Store?
> Do you have many plugins. Any which may effect usage?
> What MyBB version are you on?
> 
> Also can you try the following edit of the test.php file and then goto the test page again and see results
> 
> ```
> <?php
> 
> echo $_SERVER["HTTP_CF_CONNECTING_IP"]."\n";
> echo $_SERVER['REMOTE_ADDR'];
> 
> if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
>   	$_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
> 	}
> 
> echo $_SERVER["HTTP_CF_CONNECTING_IP"]."\n";
> echo $_SERVER['REMOTE_ADDR'];
> 
> ?>
> ```

Yes download plugin mybb store
Do you have many plugins. Any which may effect usage? (I'dont now I guess not)
What MyBB version are you on? (1.8.22)
Latest test php result
88.230.x.x - 162.158.34.xx - 88.230.x.x - 88.230.x.x
Original  -    Cloudflare  -  Original  -   Original

**Comment by JeremyCrookshank** [comment]
Okay, that's intresting. The code you've just ran is what the plugin does to restore the IP so it looks like you might have a plugin which is causing issues. Or perhaps a theme? 

Also what plugin version are you on? Can you show me the IP History plugin settings too please

**Comment by Casper2641** [comment]
> Okay, that's intresting. The code you've just ran is what the plugin does to restore the IP so it looks like you might have a plugin which is causing issues. Or perhaps a theme?
> 
> Also what plugin version are you on? Can you show me the IP History plugin settings too please

https://community.mybb.com/mods.php?action=download&pid=1213
I'm using Version 1.3.0
I removed the plugin, sorry I can't access the logs. :(

**Comment by JeremyCrookshank** [comment]
Closing as can't help without additional infomation. Feel free to retry!

**Comment by PlatinMTA** [comment]
I found the solution to this issue. To lazy to make a PR so I will tell you what I changed.

In line 63 of ip_history_logs.php, you need to change:
```php
$ip = $db->escape_binary(my_inet_pton(filter_input(INPUT_SERVER, 'REMOTE_ADDR')));
```

To:
```php
$ip = $db->escape_binary(my_inet_pton($_SERVER['REMOTE_ADDR']));
```

This will give you the correct address.
