### ISSUE TITLE
ip is not recorded 

### ISSUE THREAD

**Issue by androidloverbe** [JeremyCrookshank/IP_History_Logs#15]
Hello,

The user ip is not recorded you need to update your code in /inc/ip_history_logs.php from

$ip = my_inet_pton(filter_input(INPUT_SERVER, 'REMOTE_ADDR')); to
$ip = my_inet_pton(get_ip());

**Comment by JeremyCrookshank** [comment]
Tested both current and your suggestion and they worked the same for my forum, get_ip seems to be mybb's new standard so i've switched it now.
