### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by androidloverbe** [JeremyCrookshank/IP_History_Logs#17]
Hello,

in /inc/plugins/ip_history_logs.php more precise the ip_history_logs_activate() function the array where you define the scheduled tasks contains an error or rather a "beauty error" (typo) 

$new_task = array(
		"title"			=> "IP History Log Removal",
		"description"	=> "Automatically remove IP history logs based on days elapsed. Configured in settings.",
		"file"			=> "ip_history", //  <<== ip_history_logs
		"minute"		=> "0",
		"hour"			=> "0",
		"day"			=> "*",
		"month"			=> "*",
		"weekday"		=> "*",
		"enabled"		=> 1,
		"logging"		=> 1,
		"locked"		=> 0
	);

MyBB will generate emails complaining about that

**Comment by JeremyCrookshank** [comment]
This is fixed now. Thanks!
