### ISSUE TITLE
MYSQL Error on install

### ISSUE THREAD

**Issue by Eisteed** [JeremyCrookshank/IP_History_Logs#2]
MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

Unabled to find any log about the error o.O
This only happen when trying to install IP history logs

**Comment by JeremyCrookshank** [comment]
What version of MyBB are you on?
Are you upgrading from a previous version of IP History logs?
Have you checked for an error log in 
/admin/
OR the root of your site?

**Comment by Eisteed** [comment]
I'm using mybb 1.8.19, not upgrading from any previous version (first install)
I found error.log in admin folder indeed (didn't know that one)

MyBB SQL Error

SQL Error: 1067 - Invalid default value for 'date'
Query: CREATE TABLE IF NOT EXISTS `mybb_ip_history` (
      `id` int(10) unsigned NOT NULL auto_increment,
      `uid` int(10) NOT NULL,
      `ip` VARBINARY(16) NOT NULL,
      `page` VARCHAR(512) NULL,
	  `useragent` varchar(255) NULL,
	  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY  (`id`)
    ) ENGINE=MyISAM  
      COLLATE=utf8_general_ci
	  DEFAULT CHARSET=utf8;

MySQLi 5.5.62
PHP 7.0.30

**Comment by JeremyCrookshank** [comment]
Hey,

So the issue is with your Database version, as you're running on an older version of it, where TIMESTAMP wasn't supported in a datetime field unfourten.y

I'll see if I can get a fix implemented soon however might be a good idea to upgrade the DB as well!

**Comment by Eisteed** [comment]
I'm a bit afraid of breaking my whole server with a db upgrade wich I have never done before. I'll try to read more info about that. Hope you can find some fix :D but I guess changing this changes other stuff in the rest of the plugin. Anyway thank you !

**Comment by JeremyCrookshank** [comment]
Give the new version a try I think it should solve your problems. I also did a big update overall so I hope you like it.

Cheers

**Comment by Eisteed** [comment]
Thanks a lot ! Working Perfectly !! Waited so long for some plugin like this :) Really great job.

**Comment by JeremyCrookshank** [comment]
You're welcome.
