### ISSUE TITLE
MySQL errors during login - IP-address is garbled (v1.4.0)

### ISSUE THREAD

**Issue by AlekzNet** [JeremyCrookshank/IP_History_Logs#20]
These are the errors I see in the log:

```txt
<error>
        <dateline>1628421916</dateline>
        <script></script>
        <line>0</line>
        <type>20</type>
        <friendly_type>MyBB SQL Error</friendly_type>
        <message>SQL Error: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use
 near '?' AND uid='14912'' at line 1
Query: SELECT COUNT(*) as 'unique' FROM mybb_ip_history WHERE IP='X<D0>'<92>' AND uid='14912'</message>
        <back_trace>#0  errorHandler->error() called at [/inc/db_mysqli.php:597]
#1  DB_MySQLi->error() called at [/inc/db_mysqli.php:337]
#2  DB_MySQLi->query() called at [/inc/db_mysqli.php:789]
#3  DB_MySQLi->simple_select() called at [/inc/plugins/ip_history_logs.php:85]
#4  ip_history_logs_record_ip() called at [/inc/class_plugins.php:142]
#5  pluginSystem->run_hooks() called at [/global.php:100]
#6  require_once() called at [/attachment.php:14]
</back_trace>
</error>

<error>
        <dateline>1628434796</dateline>
        <script></script>
        <line>0</line>
        <type>20</type>
        <friendly_type>MyBB SQL Error</friendly_type>
        <message>SQL Error: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '20766'' at line 1
Query: SELECT COUNT(*) as 'unique' FROM mybb_ip_history WHERE IP='J׬\' AND uid='20766'</message>
        <back_trace>#0  errorHandler->error() called at [/inc/db_mysqli.php:597]
#1  DB_MySQLi->error() called at [/inc/db_mysqli.php:337]
#2  DB_MySQLi->query() called at [/inc/db_mysqli.php:789]
#3  DB_MySQLi->simple_select() called at [/inc/plugins/ip_history_logs.php:85]
#4  ip_history_logs_record_ip() called at [/inc/class_plugins.php:142]
#5  pluginSystem->run_hooks() called at [/global.php:100]
#6  require_once() called at [/showthread.php:28]
</back_trace>
</error>
```

Does something happen with the IP-addresses during processing?

**Comment by JeremyCrookshank** [comment]
What version are you on?

**Comment by AlekzNet** [comment]
1.4.0 - it's in the title.

**Comment by AlekzNet** [comment]
1.4.0 is what's available on mybb.com. I've just pulled the latest from git. I see it should be fixed 3 months ago and the current version is 1.4.2 :D Sorry for the trouble! WiIl let you know how it  goes!

**Comment by JeremyCrookshank** [comment]
Haha no worries! I do believe this will solve your problem. If I don't hear from you within a week I will assume it's resolved your problem

**Comment by AlekzNet** [comment]
No errors so far, but I discovered that in `Tools & Maintenance -> IP History Logs` all IP addresses look like this: 

```
X'ad0546dd'
X'ab3a57d7'
X'4a002a57' 
```
There was no such problem on 1.4.0.

**Comment by JeremyCrookshank** [comment]
It should be backwards compatible. Can you show me a picture of the above ip's in the history dash? Have you definitely got all the updated files correctly(mainly admin/modules/tools/ip_history_logs.php) specifically line 74 
`$isValid = filter_var($IP, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4);`

If you do have that line try replace it with 
`$isValid = filter_var($IP, FILTER_VALIDATE_IP);`

**Comment by JeremyCrookshank** [comment]
I'd check the above first but after If you fancy trying editing you can try this temporarily:

Open file:admin/modules/tools/ip_history_logs.php

Replace the function on line 72 with the below function

```
function HandleIP($IP) {

		if (isBinary($IP)) {
		return my_inet_ntop($IP);
		} else {
			return $IP;
		}
```

See if the IP's(Older ones display correctly)

**Comment by AlekzNet** [comment]
Unless I miss something, this is exactly how this function is defined:

```php
        function HandleIP($IP) {

                if (isBinary($IP)) {
                return my_inet_ntop($IP);
                } else {
                        return $IP;
                }
        }

```

**Comment by AlekzNet** [comment]
Is it possible, that the binaries are not correctly defined:


```php        
function isBinary($str) {
    return preg_match('~[^\x20-\x7E\t\r\n]~', $str) > 0;
 }
```

**Comment by AlekzNet** [comment]
Unistalled, re-pulled, reuploaded, re-installed - now there is no IP-address in the `Tools & Maintenance -> IP History Logs` at all - just an empty field :rofl:  The user name, UID, Useragent are logged. 

I tried with both `$isValid = filter_var($IP, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4);` and `$isValid = filter_var($IP, FILTER_VALIDATE_IP);`

![IP_history_logs-01](https://user-images.githubusercontent.com/10780668/128967449-9860c1a8-a8a5-4745-b77a-1811d8bfbe99.png)

**Comment by JeremyCrookshank** [comment]
> 
> 
> Unless I miss something, this is exactly how this function is defined:
> 
> ```
>         function HandleIP($IP) {
> 
>                 if (isBinary($IP)) {
>                 return my_inet_ntop($IP);
>                 } else {
>                         return $IP;
>                 }
>         }
> ```

Did you just not upload the latest version for this? Was it dl'd from mybb or github?

**Comment by JeremyCrookshank** [comment]
It's really odd these problems you're having as it does work out of the box. What happens if you use the old function? The fact its blank maybe suggests that there is nothing stored in the database now or a different issue for you.

If you're able to query the database please try "SELECT * FROM ip_history WHERE uid = 15761"

Please also verify you 100% have overwritten ALL plugin files with latest version(1.4.2)

```
 function HandleIP($IP) {

                if (isBinary($IP)) {
                return my_inet_ntop($IP);
                } else {
                        return $IP;
                }
        }
```

**Comment by AlekzNet** [comment]
Yes, you are and you were right. After I posted this: https://github.com/JeremyCrookshank/IP_History_Logs/issues/20#issuecomment-896359805 I checked the function, reuploaded, and it became this:

```php
        function HandleIP($IP) {
            global $db;^M
               $isValid = filter_var($IP, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4);
                if (isBinary($IP) || !$isValid) {
                return my_inet_ntop($db->unescape_binary($IP));
                } else {
                        return $IP;
                }
        }
```
This query:

```sql
SELECT * FROM `mybb_ip_history` WHERE uid='15761'
```

results in IP = 5727353361236364663329

I will try with the old function...

**Comment by JeremyCrookshank** [comment]
Thanks for doing that. I'm just spinning up a new forum just to test it further. In the meantime is there anything in your error log?

**Comment by AlekzNet** [comment]
> is there anything in your error log?

No, no errors...

**Comment by JeremyCrookshank** [comment]
Okay seems to be a problem, will get it fixed aspa thanks 👍

**Comment by JeremyCrookshank** [comment]
Alright updated the current version(on git only atm) can you please give it ago! MyBB has a weird system where I have to essentially whitelist the ip as we store them in binary so it was double escaping it. Should be fixed now please let me know

**Comment by AlekzNet** [comment]
It's working perfectly now! Thanks much for the great plugin and great support!!!!

**Comment by JeremyCrookshank** [comment]
Haha yes!! Thanks for making the report. Glad we got there in the end. Let me know any other issues
