### ISSUE TITLE
No Log File Under Tools & Maintenance

### ISSUE THREAD

**Issue by thunderclap82** [JeremyCrookshank/IP_History_Logs#3]
I've installed the plugin and it's configured and activated, but there isn't a log anywhere in Tools & Maintenance for user IP. Did I miss something?

**Comment by JeremyCrookshank** [comment]
Are you sure you have permissions to view it? 

In MyBB admin area goto Users & Groups. Click Admin Permissions on the left side bar. Click your admin profile then options -> Edit Permissions.

Then goto the Tools & Maintenance tab and ensure that "Ability to view Users IP History" is ticked yes.

Let me know if this resolves it.

**Comment by thunderclap82** [comment]
Doh! That fixed it. I always forget about that area to enable for admin. Thanks!

One thing I'd recommend is adding the username to the list, not just the user id. It would make finding a specific user a little easier. Otherwise, great work!

**Comment by JeremyCrookshank** [comment]
You're welcome. I'll add your suggestion in. Any other suggestions as I have a build to go up soon.

Follow me on twitter to get the latest updates on my MyBB projects and others: https://twitter.com/_JCrookshank

Cheers
