### ISSUE TITLE
SQL table creation precepts and optimization

### ISSUE THREAD

**Issue by crazycatdevs** [JeremyCrookshank/IP_History_Logs#4]
Hi,
This is not really an issue but some good practices you may adopt for your table creation.

1. Do not use the ` to encapsulate table and columns names, it's not a SQL standard
2. Do not use reserved keywords (as _date_) for names (goes with previous point)
3. _id_ could be too generic, you'd better choose iid (for IP Id)

Regards

**Comment by JeremyCrookshank** [comment]
Fixed in latest version. Thanks for feedback
