### ISSUE TITLE
input field for auto search of users

### ISSUE THREAD

**Issue by metulburr** [JeremyCrookshank/IP_History_Logs#7]
It would be nice to have an input field for username so you can see what your searching. IF you have a large userbase, it gets jumbled and you have to backspace but are unable to see where you are at because its not an input field.

**Comment by JeremyCrookshank** [comment]
Sorry I don't understand your request completely. Can you explain more please

**Comment by metulburr** [comment]
Sorry my fault. I didnt know you can type on the username drop-down menu to type in the person name.
